update=11/11/2018 08:52:30
last_client=kicad
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=C:/Users/Marco/Documents/Kicad/Kicad/kicad-symbols-master/Connector_Specialized
LibName2=C:/Users/Marco/Documents/Kicad/Kicad/kicad-symbols-master/Device
LibName3=C:/Users/Marco/Documents/Kicad/Kicad/kicad-symbols-master/power
LibName4=C:/Users/Marco/Documents/Kicad/Kicad/kicad-symbols-master/Connector_Generic
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
